Repository visgl/luma.gl, pull requests merged in 2018-06, with the labels that each got.

#534 New RFCs for v6.0
  dev-docs/RFCs/README.md
  dev-docs/RFCs/v6.0/offscreen-render-rfc.md
  dev-docs/RFCs/v6.0/portable-glsl-300-rfc.md
  dev-docs/RFCs/v6.0/vertex-array-attributes-rfc.md
Labels: doc

#528 Shadertools doc refresh - First pass
  docs/api-reference/shadertools/shadertools-roadmap.md
  docs/developer-guide/shadertools/README.md
  docs/developer-guide/shadertools/glsl.md
  docs/developer-guide/shadertools/using-shader-modules.md
  docs/developer-guide/shadertools/writing-shader-modules.md
Labels: chore, doc

#545 Fix unit tests
  src/webgl-context/polyfill-vertex-array-object.js
  test/src/core/experimental/transform.spec.js
Labels: test

#549 Update Picking Module to use GLSL 300 syntax
  examples/core/transform/app.js
  src/shadertools/src/modules/picking/picking.js
Labels: code

#552 Prep diff: code reorganization
  docs/api-reference/core/shader-cache.md
  docs/whats-new.md
  examples/lessons/09/app.js
  examples/test/tree-shaking/app.js
  src/core/shader-cache.js
  src/core/transform.js
  src/index.js
  src/shadertools/src/index.js
  src/shadertools/test/index.js
  src/webgl-context/create-browser-context.js
  src/webgl-utils/README.md
  src/webgl-utils/constants-to-keys.js
  src/webgl/program.js
  src/webgl/resource.js
  src/webgl/vertex-array.js
  test/src/core/index.js
  test/src/core/shader-cache.spec.js
  test/src/core/transform.spec.js
  test/start.js
  website/contents/pages.js
Labels: chore

#558 Doc Improvements
  docs/api-reference/webgl/buffer.md
  docs/api-reference/webgl/fence-sync.md
  docs/api-reference/webgl/framebuffer.md
  docs/api-reference/webgl/program.md
  docs/api-reference/webgl/query.md
  docs/api-reference/webgl/transform-feedback.md
  docs/api-reference/webgl/uniform-buffer-layout.md
  docs/api-reference/webgl/vertex-array.md
  docs/developer-guide/attributes.md
  docs/developer-guide/buffers.md
  docs/developer-guide/programs-and-shaders.md
Labels: chore, doc

#559 VertexArray #1: Light code reorg
  docs/api-reference/core/attribute.md
  src/core/attribute.js
  src/core/model.js
  src/core/transform.js
  src/index.js
  src/webgl-utils/attribute-utils.js
  src/webgl/index.js
  src/webgl/uniform-buffer-layout.js
  test/index-webgl-dependent-tests.js
  test/src/core/attribute.spec.js
  test/src/core/index.js
  test/src/experimental/index.js
  test/src/webgl/index.js
  test/src/webgl/uniform-buffer-layout.spec.js
  website/contents/pages.js
Labels: chore

#554 Make polyfills for webgl1 optional (Dist Size Reduction)
  docs/developer-guide/configuring.md
  docs/upgrade-guide.md
  docs/whats-new.md
  package.json
  src/webgl-context/index.js
  src/webgl-context/track-context-state.js
  src/webgl/query.js
  src/webgl1/index.js
  src/webgl1/polyfill-context.js
  src/webgl1/polyfill-get-parameter.js
  src/webgl1/polyfill-vertex-array-object.js
  src/webgl1/webgl-rendering-context.js
  src/wip/track-context-creation.js
  test/index-webgl-dependent-tests.js
  test/src/webgl-context/context-limits.spec.js
  test/src/webgl-context/index.js
  test/src/webgl/framebuffer.spec.js
  test/src/webgl/renderbuffer.spec.js
  test/src/webgl/texture.spec.js
  test/src/webgl1/index.js
  test/src/webgl1/polyfill-context.spec.js
  test/src/webgl1/polyfill-get-parameter.spec.js
  test/start.js
  webgl1.js
Labels: code, doc

#571 Minor cleanup for 6.0
  dev-docs/RFCs/v6.1/reduce-distribution-size-rfc.md
  dev-docs/RFCs/v6.1/shadertools-improvements-rfc.md
  docs/upgrade-guide.md
  examples/core/cubemap/app.js
  examples/core/fragment/concentrics-demo.js
  src/webgl/framebuffer.js
  src/webgl/index.js
  src/webgl/sampler.js
  test/index-webgl-dependent-tests.js
Labels: chore

#577 Fixes for deck.gl integration.
  src/core/model.js
  src/webgl/buffer.js
Labels: chore

#580 Fix ocular website
  examples/core/instancing/app.js
  examples/core/transform/app.js
  examples/lessons/01/app.js
  src/core/animation-loop.js
  website-ocular/src/demos.js
  website-ocular/src/mdRoutes.js
  website-ocular/src/react-demos-require.js
  website-ocular/src/react-demos.js
Labels: chore, doc

#582 Fix buffer reuse
  docs/api-reference/webgl/vertex-array.md
  docs/whats-new.md
  src/core/attribute.js
  src/webgl/vertex-array.js
  website-ocular/TODO.md
Labels: bug

#585 Transform updates
  docs/api-reference/core/transform.md
  examples/core/transform/app.js
  src/core/transform.js
  src/webgl-utils/index.js
  src/webgl-utils/shader-utils.js
  test/src/core/transform.spec.js
  test/src/webgl-utils/index.js
  test/src/webgl-utils/shader-utils.spec.js
Labels: enhancement
