Repository visgl/luma.gl, pull requests merged in 2018-04, with the labels that each got.

#480 Update examples to webpack 4
  examples/core/cubemap/app.js
  examples/core/cubemap/package.json
  examples/core/cubemap/webpack.config.js
  examples/core/fragment/package.json
  examples/core/fragment/webpack.config.js
  examples/core/picking/package.json
  examples/core/shadowmap/package.json
  examples/core/transform-feedback-instanced/webpack.config.js
  examples/core/transform-feedback/webpack.config.js
  examples/lessons/01/package.json
  examples/lessons/01/webpack.config.js
  examples/lessons/02/package.json
  examples/lessons/02/webpack.config.js
  examples/lessons/03/package.json
  examples/lessons/03/webpack.config.js
  examples/lessons/04/package.json
  examples/lessons/04/webpack.config.js
  examples/lessons/05/package.json
  examples/lessons/05/webpack.config.js
  examples/lessons/06/package.json
  examples/lessons/06/webpack.config.js
  examples/lessons/07/package.json
  examples/lessons/07/webpack.config.js
  examples/lessons/08/package.json
  examples/lessons/08/webpack.config.js
  examples/lessons/09/package.json
  examples/lessons/09/webpack.config.js
  examples/lessons/10/webpack.config.js
  examples/lessons/11/webpack.config.js
  examples/lessons/12/webpack.config.js
  examples/lessons/13/webpack.config.js
  examples/lessons/14/webpack.config.js
  examples/lessons/15/webpack.config.js
  examples/lessons/16/package.json
  examples/lessons/16/webpack.config.js
  examples/webpack.config.local.js
  examples/wip/custom-picking/package.json
  examples/wip/deferred-rendering/package.json
  examples/wip/particles/package.json
  examples/wip/persistence/package.json
  examples/wip/voronoi/package.json
Labels: chore

#481 Clean up debug mode
  aliases.js
  debug.js
  docs/developer-guide/building-apps.md
  package.json
  src/debug.js
  src/webgl-utils/debug-parameters.js
  src/webgl-utils/headless-gl.js
  src/webgl-utils/index.js
  src/webgl-utils/webgl-types.js
  src/webgl/api/README.md
  test/src/webgl-utils/contants.spec.js
  test/src/webgl-utils/debug.spec.js
  test/src/webgl-utils/index.js
Labels: chore

#464 PickingModule: Add picking_filterColor method
  examples/core/instancing/app.js
  src/shadertools/modules/picking/README.md
  src/shadertools/modules/picking/picking.js
Labels: code, doc

#483 Fixes to electron support and AnimationLoop debug mode
  src/core/animation-loop.js
  src/index.js
  src/init.js
  src/utils/index.js
  src/utils/is-browser.js
  src/utils/is-electron.js
  src/webgl-utils/debug-context.js
  src/webgl-utils/set-parameters.js
  src/webgl-utils/track-context-state.js
  src/webgl/context.js
  test/src/webgl/index.js
Labels: bug

#486 Delete duplicate file
  src/webgl/helpers/format-glsl-error.js
Labels: chore

#492 fix webpack file for example 14 and 15
  examples/lessons/14/webpack.config.js
  examples/lessons/15/webpack.config.js
Labels: chore

#499 Updates on master for 5.2.0-beta.2
  CHANGELOG.md
  package.json
Labels: chore

#506 VertexArray docs, initial cleanup round
  docs/api-reference/webgl/vertex-array.md
  src/webgl/vertex-array.js
  test/src/webgl/vertex-array.spec.js
Labels: doc

#507 Add markdown lint. Start adressing warnings
  .markdownlintrc
  docs/api-reference/advanced/vertex-attributes.md
  docs/api-reference/advanced/webgl-bindings.md
  docs/api-reference/webgl/transform-feedback.md
  docs/api-reference/webgl/uniform-buffer-layout.md
  docs/developer-guide/building-apps.md
  docs/developer-guide/debugging.md
  docs/get-started/README.md
  docs/get-started/installation.md
  docs/get-started/using-with-node.md
  docs/upgrade-guide.md
  docs/whats-new.md
  package.json
  scripts/lint-markdown.sh
  yarn.lock
Labels: chore, doc
