Repository visgl/luma.gl, pull requests merged in 2018-03, with the labels that each got.

#418 Transform: Add updateBuffers method
  docs/api-reference/core/experimental/transform.md
  src/core/experimental/transform.js
  test/core/experimental/transform.spec.js
Labels: code, doc

#433 Update TF demo to use new Transform class
  examples/core/transform-feedback-instanced/app.js
Labels: code

#436 Use probe.gl for logging
  package.json
  src/core/model.js
  src/utils/index.js
  src/utils/log.js
  src/utils/old-log.js
  src/webgl/uniforms.js
  test/bench/index.js
  webpack.config.js
  yarn.lock
Labels: code

#439 webgl-debug: conditional bundling
  debug.js
  docs/get-started/debugging.md
  docs/upgrade-guide.md
  docs/whats-new.md
  package.json
  src/debug.js
  src/webgl/context-debug.js
Labels: code, doc

#438 Enhanced use of probe.gl library
  package.json
  src/core/animation-loop.js
  src/core/experimental/transform.js
  src/core/model.js
  src/core/pick-models.js
  src/deprecated/headless.js
  src/init.js
  src/shadertools/lib/assemble-shaders.js
  src/utils/log.js
  src/utils/old-log.js
  src/webgl-utils/create-canvas.js
  src/webgl/context-debug.js
  src/webgl/context.js
  src/webgl/framebuffer.js
  src/webgl/program.js
  src/webgl/shader.js
  src/webgl/texture.js
  src/webgl/uniforms.js
  src/webgl/vertex-array.js
  src/webgl/vertex-attributes.js
  yarn.lock
Labels: code

#440 fix example 08 with controls
  examples/lessons/08/app.js
  examples/lessons/08/index.html
Labels: chore

#445 Fix uniform unit tests
  src/webgl/context.js
  test/webgl/uniforms.spec.js
Labels: test

#446 Dist size #1/3: Move tests into test/src
  packages/io/test/read-image.js
  packages/io/test/write-read-image.js
  test/index-webgl-dependent-tests.js
  test/index-webgl-independent-tests.js
  test/node.js
  test/src/core/experimental/transform.spec.js
  test/src/core/index.js
  test/src/debug/seer-integration.js
  test/src/deprecated/index.js
  test/src/experimental/index.js
  test/src/geometry/geometry-spec.js
  test/src/geometry/index.js
  test/src/io/index.js
  test/src/io/read-texture.js
  test/src/shadertools/index.js
  test/src/shadertools/lib/assemble-shaders.spec.js
  test/src/shadertools/lib/index.js
  test/src/shadertools/lib/shader-cache.spec.js
  test/src/shadertools/lib/shader-modules.spec.js
  test/src/shadertools/modules.js
  test/src/utils/index.js
  test/src/utils/utils.spec.js
  test/src/webgl-utils/contants.spec.js
  test/src/webgl-utils/data/sample-enum-settings.js
  test/src/webgl-utils/format-glsl-error.spec.js
  test/src/webgl-utils/get-error.spec.js
  test/src/webgl-utils/get-shader-name.spec.js
  test/src/webgl-utils/index.js
  test/src/webgl-utils/polyfill-context.spec.js
  test/src/webgl-utils/polyfill-get-parameter.spec.js
  test/src/webgl-utils/set-parameters.spec.js
  test/src/webgl-utils/track-context-state.spec.js
  test/src/webgl/buffer.spec.js
  test/src/webgl/context-features.spec.js
  test/src/webgl/context-limits.spec.js
  test/src/webgl/context-no-headless.spec.js
  test/src/webgl/context-state.spec.js
  test/src/webgl/context.spec.js
  test/src/webgl/data/sample-function-settings.js
  test/src/webgl/draw.spec.js
  test/src/webgl/framebuffer.spec.js
  test/src/webgl/helpers/query-manager.spec.js
  test/src/webgl/index.js
  test/src/webgl/program.spec.js
  test/src/webgl/query.spec.js
  test/src/webgl/renderbuffer.spec.js
  test/src/webgl/sampler.spec.js
  test/src/webgl/sampler.utils.js
  test/src/webgl/texture-2d-array.spec.js
  test/src/webgl/texture-2d.spec.js
  test/src/webgl/texture-3d.spec.js
  test/src/webgl/texture-cube.spec.js
  test/src/webgl/texture.spec.js
  test/src/webgl/transform-feedback.spec.js
  test/src/webgl/uniform-buffer-layout.spec.js
  test/src/webgl/uniforms.spec.js
  test/src/webgl/vertex-array.spec.js
  webpack.config.js
Labels: chore

#447 Dist size #2/3: Add test-size script for bundle size testing
  aliases.js
  package.json
  test/node.js
  test/size/import-nothing.js
  test/webpack.config.js
  yarn.lock
Labels: chore

#444 Fix shader compilation issues in IE 11
  src/index.js
  src/shadertools/lib/platform-defines.js
  src/utils/index.js
  src/utils/is-old-ie.js
  src/webgl/context-features.js
  test/src/utils/index.js
  test/src/utils/is-old-ie.spec.js
  test/src/webgl/context-features.spec.js
Labels: code, test

#452 Example 15
  examples/lessons/15/app.js
  examples/lessons/15/earth-specular.gif
  examples/lessons/15/earth.jpg
  examples/lessons/15/index.html
  examples/lessons/15/package.json
  examples/lessons/15/webpack.config.js
  examples/wip/15/app.js
  examples/wip/15/index.html
Labels: chore

#449 Dist Size #3/3: Add babel-minify. Remove use of external `assert`. Misc dist size changes.
  .babelrc
  package.json
  src/core/animation-loop.js
  src/core/experimental/transform.js
  src/core/group.js
  src/core/model.js
  src/core/object-3d.js
  src/core/pick-models.js
  src/debug.js
  src/geometry/geometry.js
  src/index.js
  src/io/load-files.js
  src/shadertools/lib/assemble-shaders.js
  src/shadertools/lib/shader-cache.js
  src/shadertools/lib/shader-modules.js
  src/utils/assert.js
  src/utils/format-value.js
  src/utils/index.js
  src/utils/old-log.js
  src/utils/utils.js
  src/webgl-utils/constants-to-keys.js
  src/webgl-utils/create-context.js
  src/webgl-utils/headless-gl.js
  src/webgl-utils/polyfill-context.js
  src/webgl-utils/set-parameters.js
  src/webgl-utils/track-context-state.js
  src/webgl/buffer.js
  src/webgl/clear.js
  src/webgl/context-debug.js
  src/webgl/context-features.js
  src/webgl/context-state.js
  src/webgl/context.js
  src/webgl/draw.js
  src/webgl/framebuffer.js
  src/webgl/functions.js
  src/webgl/helpers/attribute-utils.js
  src/webgl/program.js
  src/webgl/renderbuffer.js
  src/webgl/resource.js
  src/webgl/shader.js
  src/webgl/texture-cube.js
  src/webgl/texture.js
  src/webgl/transform-feedback.js
  src/webgl/uniform-buffer-layout.js
  src/webgl/uniforms.js
  src/webgl/vertex-array.js
  test/webpack.config.js
  wip/vertex-attributes.js
  yarn.lock
Labels: chore

#461 Disable babel minification (temporarily)
  .babelrc
  CHANGELOG.md
  package.json
  src/webgl-utils/headless-gl.js
Labels: bug

#450 WebGL2 : Add asynchronous mode for readPixels using PBOs.
  docs/api-reference/webgl/framebuffer.md
  docs/whats-new.md
  src/webgl/framebuffer.js
  src/webgl/helpers/format-utils.js
  test/src/webgl/framebuffer.spec.js
Labels: code, doc

#467 Do not delete Program objects
  src/shadertools/lib/shader-cache.js
  src/webgl/program.js
  test/src/shadertools/lib/shader-cache.spec.js
  test/src/webgl/program.spec.js
Labels: code

#469 Do not delete Program objects (#467)
  src/shadertools/lib/shader-cache.js
  src/webgl/program.js
  test/shadertools/lib/shader-cache.spec.js
  test/webgl/program.spec.js
Labels: code, test

#465 Collect metrics
  aliases.js
  package.json
  test/scripts/collect-metrics.sh
  test/size/import-nothing.js
  test/webpack.config.js
  yarn.lock
Labels: test

#472 Allow null uniforms
  src/webgl/uniforms.js
Labels: code

#473 Fix Uniform Buffer binding
  src/webgl/buffer.js
  test/src/webgl/buffer.spec.js
Labels: code

#468 Integrate test-browser with "git commit"
  .travis.yml
  package.json
  yarn.lock
Labels: chore
