Repository visgl/luma.gl, pull requests merged in 2018-08, with the labels that each got.

#624 Rename export: _Transform to Transform
  docs/api-reference/core/transform.md
  docs/developer-guide/transform-feedback.md
  docs/upgrade-guide.md
  examples/core/transform/app.js
  modules/core/src/index.js
  test/modules/core/core/transform.spec.js
  test/modules/core/shadertools/fp64/fp64-test-utils-transform.js
  test/modules/core/webgl/uniform-buffer-layout.spec.js
Labels: chore

#650 Fix browser tests
  modules/core/src/core/model.js
  modules/core/src/core/transform.js
  modules/core/src/shadertools/test/lib/assemble-shaders.spec.js
  modules/core/src/webgl-debug/debug-uniforms.js
  modules/core/src/webgl-debug/debug-vertex-array.js
  modules/core/src/webgl/accessor.js
  modules/core/src/webgl/program-configuration.js
  modules/core/src/webgl/uniforms.js
  modules/core/src/webgl/vertex-array.js
  package.json
  test/modules/core/shadertools/index.js
  test/modules/core/shadertools/picking.spec.js
  yarn.lock
Labels: chore

#651 Accessor cleanup
  docs/api-reference/webgl/accessor.md
  docs/developer-guide/accessors.md
  docs/developer-guide/buffers.md
  modules/core/src/webgl/accessor.js
  modules/core/src/webgl/buffer.js
  modules/core/src/webgl/program-configuration.js
  modules/core/src/webgl/vertex-array-object.js
  modules/core/src/webgl/vertex-array.js
  test/modules/core/webgl/accessor.spec.js
  test/modules/core/webgl/vertex-array.spec.js
  website/contents/pages.js
Labels: chore

#652 Attribute fixes
  modules/core/src/core/attribute.js
  test/modules/core/core/attribute.spec.js
Labels: chore

#656 Misc Vertex Array fixes.
  docs/api-reference/webgl/vertex-array.md
  examples/core/instancing/app.js
  modules/core/src/core/model.js
  modules/core/src/webgl-debug/debug-program-configuration.js
  modules/core/src/webgl-debug/debug-vertex-array.js
  modules/core/src/webgl/program-configuration.js
  modules/core/src/webgl/vertex-array-object.js
  modules/core/src/webgl/vertex-array.js
  modules/core/src/webgl1/index.js
  modules/core/src/webgl1/polyfill-context.js
  test/modules/core/core/model.spec.js
  website/contents/demos.js
  website/package.json
Labels: chore

#659 Add GLB and Point Cloud Loaders to new loaders module
  modules/loaders/package.json
  modules/loaders/src/common/loader-utils/array-utils.js
  modules/loaders/src/common/loader-utils/assert.js
  modules/loaders/src/common/loader-utils/binary.js
  modules/loaders/src/common/loader-utils/flatten.js
  modules/loaders/src/common/loader-utils/get-image-size.js
  modules/loaders/src/common/loader-utils/index.js
  modules/loaders/src/common/loader-utils/load-uri.js
  modules/loaders/src/common/loader-utils/loader-utils.js
  modules/loaders/src/common/loader-utils/memoize.js
  modules/loaders/src/common/loader-utils/stats.js
  modules/loaders/src/common/loader-utils/text-decoder.js
  modules/loaders/src/common/loader-utils/text-encoder-decoder.js
  modules/loaders/src/common/loader-utils/to-low-precision.js
  modules/loaders/src/common/loader-utils/worker-utils.js
  modules/loaders/src/common/loader.js
  modules/loaders/src/glb-loader/glb-decoder.js
  modules/loaders/src/glb-loader/glb-loader.js
  modules/loaders/src/glb-loader/unpack-glb-buffers.js
  modules/loaders/src/glb-writer/glb-buffer-packer.js
  modules/loaders/src/glb-writer/glb-encoder.js
  modules/loaders/src/glb-writer/glb-writer.js
  modules/loaders/src/glb-writer/pack-json-arrays.js
  modules/loaders/src/index.js
  modules/loaders/src/laz-loader/laslaz.js
  modules/loaders/src/laz-loader/laz-loader.js
  modules/loaders/src/laz-loader/parse-laz.js
  modules/loaders/src/laz-loader/point-cloud-utils.js
  modules/loaders/src/obj-loader/obj-loader.js
  modules/loaders/src/ply-loader/ply-loader.js
  modules/loaders/src/ply-loader/ply-process.js
  test/modules/loaders/common/index.js
  test/modules/loaders/common/loader-utils/flatten.spec.js
  test/modules/loaders/common/loader-utils/index.js
  test/modules/loaders/common/loader-utils/load-uri.spec.js
  test/modules/loaders/glb-loader/glb-encode-parse.spec.js
  test/modules/loaders/index.js
Labels: code, test

#664 Buffer Cleanup
  docs/api-reference/webgl/accessor.md
  docs/api-reference/webgl/buffer.md
  modules/core/src/utils/array-utils-flat.js
  modules/core/src/webgl/buffer.js
  test/modules/core/webgl/buffer.spec.js
  test/modules/core/webgl/index.js
  test/modules/core/webgl/vertex-array-object.spec.js
Labels: chore

#657 Add loader module RFC
  dev-docs/RFCs/README.md
  dev-docs/RFCs/v6.1/loader-module-rfc.md
  dev-docs/RFCs/v6.1/multipass-rendering-rfc.md
  dev-docs/RFCs/v6.1/transform-webgl1-support-rfc.md
Labels: doc

#687 Update whats new
  docs/whats-new.md
Labels: chore, doc

#691 Rename loaders directory
  test/index-webgl-independent-tests.js
  test/modules/loaders.gl/common/index.js
  test/modules/loaders.gl/common/loader-utils/flatten.spec.js
  test/modules/loaders.gl/common/loader-utils/index.js
  test/modules/loaders.gl/common/loader-utils/load-uri.spec.js
  test/modules/loaders.gl/common/smart-fetch.spec.js
  test/modules/loaders.gl/glb-loader/glb-builder.spec.js
  test/modules/loaders.gl/glb-loader/glb-encode-parse.spec.js
  test/modules/loaders.gl/glb-loader/glb-encoder-decoder.spec.js
  test/modules/loaders.gl/glb-loader/index.js
  test/modules/loaders.gl/glb-loader/pack-binary-json.spec.js
  test/modules/loaders.gl/glb-loader/test-data.json
  test/modules/loaders.gl/index.js
  test/modules/loaders.gl/kml-loader/KML_Samples.kml.js
  test/modules/loaders.gl/kml-loader/kml-loader.spec.js
  test/modules/loaders.gl/pcd-loader/README.md
  test/modules/loaders.gl/pcd-loader/Zaghetto.pcd
  test/modules/loaders.gl/pcd-loader/pcd-loader.spec.js
  test/modules/loaders.gl/pcd-loader/simple-ascii.pcd.js
Labels: chore

#697 Safari fixes
  modules/core/package.json
  modules/core/src/webgl/program.js
  modules/core/src/webgl/vertex-array.js
  yarn.lock
Labels: bug

#701 Disable `sideEffects` field to fix minified builds
  modules/core/package.json
Labels: bug

#709 loaders.gl: Exclude `fs` in browsers
  modules/loaders.gl/package.json
  modules/loaders.gl/src/common/loader-utils/load-uri.js
  modules/loaders.gl/src/gltf-instantiator/gltf-instantiator.js
Labels: chore

#661 loaders.gl: Add DRACO decompression support
  modules/loaders.gl/package.json
  modules/loaders.gl/src/draco-encoder/draco-encoder.js
  modules/loaders.gl/src/draco-loader/draco-decoder.js
  modules/loaders.gl/src/draco-loader/draco-loader.js
  modules/loaders.gl/src/index.js
  test/modules/loaders.gl/data/draco/bunny.drc
  test/modules/loaders.gl/draco-encoder/draco-encoder.spec.js
  test/modules/loaders.gl/draco-loader/draco-loader.spec.js
  test/modules/loaders.gl/glb-writer/glb-builder.spec.js
  test/modules/loaders.gl/glb-writer/glb-encode-parse.spec.js
  test/modules/loaders.gl/glb-writer/glb-encoder-decoder.spec.js
  test/modules/loaders.gl/glb-writer/index.js
  test/modules/loaders.gl/glb-writer/pack-binary-json.spec.js
  test/modules/loaders.gl/index.js
  yarn.lock
Labels: code, doc, test
