Repository visgl/luma.gl, pull requests merged in 2018-02, with the labels that each got.

#408 5.1: Soft require headless-gl, remove unused utils
  src/headless.js
  src/utils/index.js
  src/utils/utils.js
  src/webgl-utils/create-canvas.js
  test/utils/utils.spec.js
Labels: impl

#409 Headless context import and creation overhaul
  docs/api-reference/webgl/context/context.md
  docs/get-started/using-with-node.md
  docs/whats-new.md
  examples/test/headless/test.js
  headless.js
  packages/io/test/read-image.js
  src/deprecated/headless.js
  src/headless.js
  src/init.js
  src/utils/index.js
  src/utils/utils.js
  src/webgl-utils/create-canvas.js
  src/webgl-utils/headless-gl.js
  src/webgl-utils/index.js
  src/webgl-utils/webgl-types.js
  src/webgl/api/index.js
  src/webgl/context.js
  src/webgl/index.js
  src/webgl/texture.js
  test/bench/node.js
  test/core/experimental/transform.spec.js
  test/geometry/geometry-spec.js
  test/io/read-texture.js
  test/node.js
  test/setup/index.js
  test/shadertools/lib/assemble-shaders.spec.js
  test/shadertools/lib/shader-cache.spec.js
  test/shadertools/lib/shader-modules.spec.js
  test/utils/utils.spec.js
  test/webgl/buffer.spec.js
  test/webgl/context.spec.js
  test/webgl/draw.spec.js
  test/webgl/framebuffer.spec.js
  test/webgl/program.spec.js
  test/webgl/renderbuffer.spec.js
  test/webgl/texture-2d-array.spec.js
  test/webgl/texture-2d.spec.js
  test/webgl/texture-3d.spec.js
  test/webgl/texture-cube.spec.js
  test/webgl/texture.spec.js
  test/webgl/transform-feedback.spec.js
  test/webgl/uniform-buffer-layout.spec.js
  test/webgl/uniforms.spec.js
Labels: impl

#422 Fix array uniform setting
  src/webgl/uniforms.js
  test/webgl/uniforms.spec.js
Labels: code

#425 Fix array uniform setting (#422)
  src/webgl/uniforms.js
  test/webgl/uniforms.spec.js
Labels: code

#427 Add the right blog link in roadmap.md
  docs/roadmap.md
Labels: doc

#428 Fix exports
  src/index.js
  src/shadertools/modules/lighting/lighting.js
  src/webgl-utils/index.js
  src/webgl/index.js
Labels: chore

#431 Fixed crash caused by wrong utils folder path
  src/deprecated/headless.js
Labels: code
