Repository visgl/luma.gl, pull requests merged in 2019-05, with the labels that each got.

#1095 Check for navigator before accessing
  modules/addons/src/webvr/vr-display.js
Labels: chore

#1104 Fix glfx example
  examples/glfx/app.js
  examples/glfx/canvas.js
  examples/glfx/index.html
  examples/glfx/webpack.config.js
  modules/script/webpack.config.js
Labels: bug

#1106 Refactor effects and glfx libs (part 1)
  modules/effects/src/experimental/modules/convolution.js
  modules/effects/src/experimental/modules/convolution.md
  modules/effects/src/experimental/modules/depth.js
  modules/effects/src/experimental/modules/depth.md
  modules/effects/src/experimental/modules/pack.js
  modules/effects/src/experimental/modules/pack.md
  modules/effects/src/experimental/modules/ssao.js
  modules/effects/src/experimental/modules/ssao.md
  modules/effects/src/experimental/passes/convolution-pass.js
  modules/effects/src/experimental/passes/outline-pass.js
  modules/effects/src/experimental/passes/ssao-pass.js
  modules/effects/src/experimental/passes/ssao-pass.md
  modules/effects/src/index.js
Labels: code

#1103 effects module RFC
  dev-docs/RFCs/v7.1/effects-module-rfc.md
Labels: doc

#1107 refactor effect and glfx libs (part2)
  examples/glfx/app.js
  lerna.json
  modules/effects/src/index.js
  modules/effects/src/modules/adjust-filters/brightnesscontrast.js
  modules/effects/src/modules/adjust-filters/denoise.js
  modules/effects/src/modules/adjust-filters/huesaturation.js
  modules/effects/src/modules/adjust-filters/noise.js
  modules/effects/src/modules/adjust-filters/sepia.js
  modules/effects/src/modules/adjust-filters/vibrance.js
  modules/effects/src/modules/adjust-filters/vignette.js
  modules/effects/src/modules/blur-filters/tiltshift.js
  modules/effects/src/modules/blur-filters/triangleblur.js
  modules/effects/src/modules/blur-filters/zoomblur.js
  modules/effects/src/modules/fun-filters/colorhalftone.js
  modules/effects/src/modules/fun-filters/dotscreen.js
  modules/effects/src/modules/fun-filters/edgework.js
  modules/effects/src/modules/fun-filters/hexagonalpixelate.js
  modules/effects/src/modules/fun-filters/ink.js
  modules/effects/src/modules/utils/random.js
  modules/effects/src/modules/warp-filters/bulgepinch.js
  modules/effects/src/modules/warp-filters/swirl.js
  modules/effects/src/modules/warp-filters/warp.js
  modules/glfx/package.json
  modules/glfx/src/index.js
  wip/src/effects/adjust-filters/unsharpmask.js
  wip/src/effects/blur-filters/lensblur.js
  wip/src/effects/curve-filters/curves.js
  wip/src/effects/curve-filters/spline-interpolator.js
  wip/src/effects/warp-filters/matrix.js
  wip/src/effects/warp-filters/matrixwarp.js
  wip/src/effects/warp-filters/perspective.js
Labels: code

#1109 refactor effect and glfx libs (part3)
  modules/effects/src/experimental/modules/convolution.js
  modules/effects/src/experimental/passes/convolution-pass.js
  modules/effects/src/index.js
Labels: code

#1115 Bump ocular-gatsby
  website-gatsby/.gitignore
  website-gatsby/ocular-config.js
  website-gatsby/package.json
  website-gatsby/src/components/site-query.jsx
  website-gatsby/templates/core/example-cubemap.jsx
  website-gatsby/templates/core/example-dof.jsx
  website-gatsby/templates/core/example-fragment.jsx
  website-gatsby/templates/core/example-gltf.jsx
  website-gatsby/templates/core/example-instancing.jsx
  website-gatsby/templates/core/example-mandelbrot.jsx
  website-gatsby/templates/core/example-persistence.jsx
  website-gatsby/templates/core/example-quasicrystals.jsx
  website-gatsby/templates/core/example-shadowmap.jsx
  website-gatsby/templates/core/example-texture-3d.jsx
  website-gatsby/templates/core/example-transform-feedback.jsx
  website-gatsby/templates/core/example-transform.jsx
  website-gatsby/templates/lessons/example-01.jsx
  website-gatsby/templates/lessons/example-02.jsx
  website-gatsby/templates/lessons/example-03.jsx
  website-gatsby/templates/lessons/example-04.jsx
  website-gatsby/templates/lessons/example-05.jsx
  website-gatsby/templates/lessons/example-06.jsx
  website-gatsby/templates/lessons/example-07.jsx
  website-gatsby/templates/lessons/example-08.jsx
  website-gatsby/templates/lessons/example-09.jsx
  website-gatsby/templates/lessons/example-10.jsx
  website-gatsby/templates/lessons/example-11.jsx
  website-gatsby/templates/lessons/example-12.jsx
  website-gatsby/templates/lessons/example-13.jsx
  website-gatsby/templates/lessons/example-14.jsx
  website-gatsby/templates/lessons/example-15.jsx
  website-gatsby/templates/lessons/example-16.jsx
Labels: chore

#1118 rename modules folder to shader-modules
  dev-docs/RFCs/v7.1/effects-module-rfc.md
  modules/effects/src/experimental/passes/ssao-pass.js
  modules/effects/src/experimental/shader-modules/convolution.js
  modules/effects/src/experimental/shader-modules/convolution.md
  modules/effects/src/experimental/shader-modules/depth.js
  modules/effects/src/experimental/shader-modules/depth.md
  modules/effects/src/experimental/shader-modules/pack.js
  modules/effects/src/experimental/shader-modules/pack.md
  modules/effects/src/experimental/shader-modules/ssao.js
  modules/effects/src/experimental/shader-modules/ssao.md
  modules/effects/src/index.js
  modules/effects/src/shader-modules/adjust-filters/brightnesscontrast.js
  modules/effects/src/shader-modules/adjust-filters/denoise.js
  modules/effects/src/shader-modules/adjust-filters/huesaturation.js
  modules/effects/src/shader-modules/adjust-filters/noise.js
  modules/effects/src/shader-modules/adjust-filters/sepia.js
  modules/effects/src/shader-modules/adjust-filters/vibrance.js
  modules/effects/src/shader-modules/adjust-filters/vignette.js
  modules/effects/src/shader-modules/blur-filters/tiltshift.js
  modules/effects/src/shader-modules/blur-filters/triangleblur.js
  modules/effects/src/shader-modules/blur-filters/zoomblur.js
  modules/effects/src/shader-modules/fun-filters/colorhalftone.js
  modules/effects/src/shader-modules/fun-filters/dotscreen.js
  modules/effects/src/shader-modules/fun-filters/edgework.js
  modules/effects/src/shader-modules/fun-filters/hexagonalpixelate.js
  modules/effects/src/shader-modules/fun-filters/ink.js
  modules/effects/src/shader-modules/utils/random.js
  modules/effects/src/shader-modules/warp-filters/bulgepinch.js
  modules/effects/src/shader-modules/warp-filters/swirl.js
  modules/effects/src/shader-modules/warp-filters/warp.js
Labels: code

#1128 glfx API audit and documentation
  docs/api-reference/effects/glfx-shader-modules.md
  docs/api-reference/effects/overview.md
  examples/glfx/app.js
  modules/effects/src/shader-modules/adjust-filters/vignette.js
  modules/effects/src/shader-modules/blur-filters/tiltshift.js
  modules/effects/src/shader-modules/blur-filters/zoomblur.js
  modules/effects/src/shader-modules/fun-filters/colorhalftone.js
  modules/effects/src/shader-modules/fun-filters/dotscreen.js
  modules/effects/src/shader-modules/fun-filters/hexagonalpixelate.js
  modules/effects/src/shader-modules/warp-filters/bulgepinch.js
  modules/effects/src/shader-modules/warp-filters/swirl.js
  website/contents/pages.js
  wip/docs/filters.md
Labels: doc
