Repository visgl/luma.gl, pull requests merged in 2019-01, with the labels that each got.

#836 phong lighting module and new lighting classes
  modules/core/src/index.js
  modules/core/src/lighting/light-source.js
  modules/core/src/materials/material.js
  modules/core/src/materials/phong-material.js
  modules/core/src/shadertools/src/index.js
  modules/core/src/shadertools/src/modules/phong-lighting/phong-lighting.glsl.js
  modules/core/src/shadertools/src/modules/phong-lighting/phong-lighting.js
Labels: code

#839 restrict scope of glsl comment remove plugin
  babel.config.js
Labels: code

#840 Fix deprecated constant export
  aliases.js
  modules/core/constants.js
  modules/core/headless.js
  package.json
  test/index-webgl-independent-tests.js
  test/modules/constants/constants.spec.js
  test/modules/constants/index.js
  yarn.lock
Labels: bug

#841 lighting docs
  docs/api-reference/lighting/ambient-light.md
  docs/api-reference/lighting/directional-light.md
  docs/api-reference/lighting/point-light.md
  docs/api-reference/material/phong-material.md
  modules/core/src/lighting/light-source.js
Labels: doc

#851 Forward shadertools exports (temporarily) to avoid breaking deck.gl
  modules/core/package.json
  modules/core/src/index.js
  modules/shadertools/package.json
Labels: bug

#852 disable lighting by default
  modules/shadertools/src/modules/phong-lighting/phong-lighting.glsl.js
  modules/shadertools/src/modules/phong-lighting/phong-lighting.js
Labels: code

#854 fix lint scripts
  package.json
  scripts/lint.sh
Labels: chore

#857 Add GLTF example with GLTF-loader working
  examples/gltf/app.js
  examples/gltf/package.json
  examples/gltf/webpack.config.js
  modules/core/src/index.js
  modules/core/src/scenegraph/gltf-instantiator/gltf-instantiator.js
  modules/core/src/scenegraph/group.js
  modules/core/src/scenegraph/mesh-model.js
  modules/core/src/scenegraph/scenegraph-node.js
Labels: feature

#868 Deprecation Fixes and Cleanup
  dev-docs/RFCs/README.md
  dev-docs/RFCs/v6.2/module-structure-rfc.md
  dev-docs/RFCs/v7.0/framebuffer-texture-api-rfc.md
  docs/api-reference/webgl/accessor.md
  docs/developer-guide/accessors.md
  docs/developer-guide/loaders.gl/README.md
  docs/developer-guide/loaders.gl/about-loaders.md
  docs/upgrade-guide.md
  modules/core/src/utils/check-props.js
  modules/core/src/utils/index.js
  modules/core/src/utils/stub-methods.js
  modules/core/src/webgl-context/debug-context.js
  modules/core/src/webgl/program.js
  modules/core/src/webgl/shader.js
  test/index-webgl-dependent-tests.js
  test/index-webgl-independent-tests.js
  test/modules/core/utils/index.js
  test/modules/core/webgl/buffer.spec.js
  test/modules/gpgpu/histopyramid.spec.js
  test/modules/gpgpu/index.js
Labels: chore
